Fix args parse for cft-diff and cft-get

diff --git a/src/cft-diff b/src/cft-diff
--- a/src/cft-diff
+++ b/src/cft-diff
@@ -1,30 +1,54 @@
 #!/bin/sh
 
-CONFIG_FILE='/etc/cft/cft.conf'
+CONFIG_FILE=/etc/cft/cft.conf
+PROG_NAME="${0##*/}"
 
-if [ "${1}" = '--config' -o "${1}" = '-c' ]; then
-  CONFIG_FILE="${2}"
-  [ "${CONFIG_FILE#/}" = "${CONFIG_FILE}" ] && CONFIG_FILE="/etc/cft/${CONFIG_FILE}"
-  [ -e "${CONFIG_FILE}" ] || CONFIG_FILE="${CONFIG_FILE%.conf}.conf"
-  shift 2
-fi
+function print_usage() {
+	echo "USAGE: ${PROG_NAME} [-c <conf_file>] [-r] <file>"
+  echo "     -c --config <conf_file>    Use config <conf_file> instead of default (${CONFIG_FILE})"
+  echo '     -r --reverse               Show diff in reverse'
+  echo '     -h --help                  Print this help'
+  exit ${1}
+}
 
-FILE="${1}"
+while [ -n "${1}" ]; do
+  case "${1}" in
+    -c|--config)
+      CONFIG_FILE="${2}"
+      [ "${CONFIG_FILE#/}" = "${CONFIG_FILE}" ] && CONFIG_FILE="/etc/cft/${CONFIG_FILE}"
+      [ -e "${CONFIG_FILE}" ] || CONFIG_FILE="${CONFIG_FILE%.conf}.conf"
+      shift
+      ;;
+    -r|--reverse)
+      REVERSE=yes
+      ;;
+    -h|--help)
+      print_usage
+      ;;
+    *)
+      if [ -z ${FILE} ]; then
+        FILE="${1}"
+      else
+        print_usage
+        echo "Unknown option ${1}" >&2
+        exit 1
+      fi
+      ;;
+  esac
+  shift
+done
 
-if [ -z "${FILE}" ]; then
-	echo "USAGE: ${0##*/} <file>"
-	exit
-fi
+[ -z "${FILE}" ] && print_usage 1
 
 source "${CONFIG_FILE}" || exit 1
 
 if [ ! -e "${FILE}" ]; then
-	echo "Local file ${FILE} not found"
+	echo "Local file ${FILE} not found" >&2
 	exit 1
 fi
 
 if [ ! -f "${FILE}" ]; then
-	echo "Local file ${FILE} is not a regular file"
+	echo "Local file ${FILE} is not a regular file" >&2
 	exit 1
 fi
 
@@ -34,6 +58,10 @@ rsync ${CFT_RSYNC_OPTS} -q \
     -e "ssh -p ${CFT_PORT:-22} ${CFT_SSH_OPTS}" \
     "${CFT_HOST}":"${CFT_ROOT}${CFT_ROOT:+/}${FILE}" "${TEMP_FILE}"
 
-diff -u "${FILE}" "${TEMP_FILE}" |tail -n +3
+if [ "${REVERSE}" = yes ]; then
+  diff -u "${TEMP_FILE}" "${FILE}" |tail -n +3
+else
+  diff -u "${FILE}" "${TEMP_FILE}" |tail -n +3
+fi
 
 rm "${TEMP_FILE}"
